### ISSUE TITLE
How to display a lot of text OR scrollable widgets?

### ISSUE THREAD

**Issue by markus1189** [jtdaugherty/vty-ui#61]
Hi,

I am currently trying to display a larger portion of text (an article).  As far as I understand it `TextWidget`s are not scrollable right?  What would be the best alternative?  I guess an `EditWidget`would be possible but I only want to display text, not edit it.

Any ideas?

Best,
Markus

**Comment by jtdaugherty** [comment]
You are correct, text widgets are not scrollable.  And while edit widgets could be used to emulate this, the editing can't be disabled directly.  I'm sorry to say that right now there is not a good way to implement what you want.  However, there is a way you can hack it:

Instead of putting your lines of text into a text widget or editor, put them into a list instead.  Set the list's attributes so the selected item looks no different from the rest, and it won't even look like a list.  But you'll get all of the scrolling support that a list offers.

**Comment by markus1189** [comment]
Okay I'll go for the list widget, thanks.
