### ISSUE TITLE
Table widget turns blank if too many rows are added

### ISSUE THREAD

**Issue by ktvoelker** [jtdaugherty/vty-ui#62]
I have a patch for this, but it's not very well-tested yet.

https://github.com/ktvoelker/vty-ui/compare/tables-calc-max-visible-rows

Do you see any problems there?

**Comment by ktvoelker** [comment]
This has also gotten me thinking about scrolling - if you've got too many rows to show all at once, how do you decide which ones to show? I can think of a few different ways it could work:

1. Just make this "max visible rows" calculation accessible to the application using the table, and leave the rest of the work to the application.
2. Support scrolling as a feature of the table widget.
3. Make a new widget called ScrollBox that can wrap the table (or anything else) and provide it with an "unbounded DisplayRegion" (at least vertically unbounded). Then the ScrollBox would clip the image.

A naive implementation of the third option could result in rendering a massive image, most of which is going to be clipped away. So I suspect that doing the third option *well* would be a lot of work.

**Comment by jtdaugherty** [comment]
Howdy!

Regarding your patch: the only issue I see is that it doesn't account for borders between rows, if they are shown.  As a result, your calculations will only be reliable with no borders shown.

The fundamental problem is that tables are not intended to show some of many rows in a collection; they are intended for layout, not for e.g. spreadsheets, which is why they aren't more flexible.  As for the disappearing table issue you cited, the general behavior of any widget in `vty-ui`is "show what you can, but reduce what you show if you run out of room."  For the table, this might mean rendering some rows with less height or width as the user resizes the terminal, but whether that works well depends entirely on the sizing policy of what went into the table in the first place.  And, as you found out, it doesn't do anything special to reduce which rows are shown.  The reason is that it's hard to know what the right thing to do is in the *general* case when someone uses a table.  I came down on the side of thinking that it would be better to show no table than to arbitrarily cut rows in the event of there not being enough room.

As for scrolling in general, this is something I'd like, but more support is needed from the underlying `vty` library.  I *think* some or all of that might be there with `vty` version 5, but I haven't had time to think deeply about how `vty-ui` might be refactored to benefit from its new features.  Scrolling is something that could be tackled in the general case in exactly the way you described in (3), and that is how I've been thinking of it whenever I mull over supporting this in the future.  The trick is, many of the widgets won't behave sensibly if given infinite space - some constraints are going to be necessary.  (An example is a scrolling text document, where the width might need to be constrained if you want to trigger line-wrapping.)  I also agree with your assessment that (3) would probably be a lot of work to get right in general.  Now you know why I have not spent much time on it! :)

**Comment by jtdaugherty** [comment]
Looking at your patch again, I'm mistaken; it appears to handle row borders. :)

**Comment by ktvoelker** [comment]
In my own application, showing "some of the many rows in a collection" is exactly what I need to do. I can understand why you don't want the table widget to be responsible for choosing that subset, but the application can't choose the subset if it doesn't know how big the subset can be.

How about adding a field to the table state of type `Int -> [TableRow] -> [TableRow]` (or perhaps `Int -> [TableRow] -> IO [TableRow]`). Then, that function would be applied in place of `take` in my patch. In other words, the field would exist to transfer the responsibility for picking the subset back onto the application.

**Comment by ktvoelker** [comment]
(I guess I should clarify that this new field I am suggesting would be settable using a function exposed by the Table module. And it could just be `take` by default.)

**Comment by jtdaugherty** [comment]
FWIW, I'm starting to prototype generalized scrolling in the `scrolling` branch.

**Comment by jtdaugherty** [comment]
(At the earliest, it'll be usable in a few days.)

**Comment by jtdaugherty** [comment]
Out of curiosity, in your table showing many rows, are there also interactive widgets, such as `Edit`?  Or is this just a table of read-only info?

**Comment by ktvoelker** [comment]
It's read-only....although I could imagine wanting to make some of the columns editable in the future.

**Comment by jtdaugherty** [comment]
If you pull the `scrolling` branch and try that, it provides a new vertical scrolling wrapper in the `VScroll` module.  It can be used to scroll anything vertically, but there are some caveats.

The first one is that it while you could use it to scroll a widget containing editable, focusable things, when those things get the focus, the cursor-placement logic gets messed up because vertical scrolling breaks the cursor-positioning model that the library assumes everywhere else.  I'm currently thinking about ways to get around this and refactor the library to handle cursor positioning in a way that would make scrolling editable interfaces work.  (There's another issue that will need to be handled, too, which is that changing focus needs to somehow trigger scrolled areas to change scroll position to reveal widgets as they receive focus.  Right now there is just no way to do this.)

The second caveat is that keyboard events to control scrolling have to be sent to the `VScroll` wrapper, but it's not a widget you'd probably want to add to your `FocusGroup`.  Although that *might* be desirable, the alternative is to use the new `ScrollVertically` type class API (see the new `Scrollable` module) to scroll the new widget from your own keyboard event handler.

**Comment by jtdaugherty** [comment]
In particular, there's now a scrolling demo application that puts a big table into a scrolling area and lets you move around it. (See `vty-ui-scroll-demo`)

**Comment by jtdaugherty** [comment]
FYI, since this package has been deprecated in favor of brick (http://hackage.haskell.org/package/brick) I'm closing open vty-ui tickets since I'd prefer to redirect users to that new (and better) library instead of spending energy on vty-ui.  (If someone wants to take up the mantle and fix them, we can just re-open the issues.)
