### ISSUE TITLE
Inserting and removing table rows

### ISSUE THREAD

**Issue by ktvoelker** [jtdaugherty/vty-ui#63]
I'm working on a project that pretty much centers around a big table whose contents are dynamic. I wrote some functions for inserting and removing rows (see https://github.com/ktvoelker/vty-ui/commit/0ddb44dd7aa85f5ef3b1d19a3f782c66ef6db051), but the interface could certainly use some more thought. I have also been pondering whether the table widget would be better off storing its rows in an MVector, but that might be overly specialized toward my particular use case.

**Comment by jtdaugherty** [comment]
I would be happy to consider patches along these lines.  Find out what works well for you and them submit a pull request.

**Comment by ktvoelker** [comment]
Will do.

**Comment by jtdaugherty** [comment]
FYI, since this package has been deprecated in favor of brick (http://hackage.haskell.org/package/brick) I'm closing open vty-ui tickets since I'd prefer to redirect users to that new (and better) library instead of spending energy on vty-ui.  (If someone wants to take up the mantle and fix them, we can just re-open the issues.)
