### ISSUE TITLE
Is there a version of this library with MonadIO signatures?

### ISSUE THREAD

**Issue by NorfairKing** [jtdaugherty/vty-ui#71]
For usual IO functions, this doesn't matter. I just add liftIO.
For functions like handlers, which expect and IO action, this is a problem.
I cannot use my own monad like this.

**Comment by jtdaugherty** [comment]
The short answer is: no, there is not an alternative version of the library that uses MonadIO.

The long answer is: if you care to dig around in the git history, a long time ago the library actually did use `MonadIO` everywhere, but it didn't last long.  The reason it didn't work out was because the type system has no way to know that the `MonadIO` instance used for registered event handlers is the same one used for everything else, and the only way to really resolve that is to make every type take a monad parameter.  You can imagine how that would cause an absolutely ridiculous explosion in type verbosity, given that we already have things like `Box (Box (List a b) FormattedText) FormattedText`.  Every type in that expression would need an extra `m` that would need to match everywhere, and *then* the `MonadIO` constraint would have to be added to all library functions.

At the time my conclusion was that as much as I wanted this to work, it wasn't worth the trade-offs needed.

But I think there is hope: there might be a design approach that would give you want you want without changing the library while also resulting in a cleaner separation of concerns.  If you have important computations that need to run in your own monad, say `StateT s IO `, run that computation in a thread that takes messages from a `Chan`.  Then have your `vty-ui` event handlers just send messages to that `Chan` in `IO`, but meanwhile your `StateT` computation takes them out of the `Chan` and does what it needs to do in the context of your monad transformer stack (or whatever).  This way you encode the specific kinds of actions to take in the `Chan` message type, and you divorce your custom monadic computation from the user interface itself.  Finally, note that the `StateT` thread (say) must use `vty-ui`'s `schedule` function to make UI changes safely.

**Comment by NorfairKing** [comment]
Thank you for your answer. The `Chan` idea was great!

**Comment by jtdaugherty** [comment]
Great! I'm glad to hear that it worked out for you.
